#!/usr/bin/env python3
# (c) 2026 Luna Ecosystem. Lead Architect: LMDtokyo.
# Licensed under GPLv3.

"""
regen_roots.py — regenerate src/stdlib/x509_roots.luna from Mozilla NSS.

Pulls the Mozilla Common CA Database (CCADB) root list (PEM bundle),
for each trusted root parses the SubjectPublicKeyInfo ASN.1 block,
hashes it with SHA-256, and emits the 32-byte fingerprint table that
x509_roots.luna uses for trust anchoring.

This is a **one-off tool** — developers run it occasionally when Mozilla
publishes a fresh root set (roughly quarterly).  The generated bytes are
committed to the repo; the running Luna binary never talks to CCADB.

# Dependencies
- Python 3.7+
- `cryptography` library (pip install cryptography)
- Internet access to https://ccadb-public.secure.force.com/mozilla/...

# Usage
    python3 bootstrap/regen_roots.py                 # write x509_roots.luna
    python3 bootstrap/regen_roots.py --dry-run       # print hashes only
    python3 bootstrap/regen_roots.py --include-test  # add test CA (ISRG staging)

# What this script does NOT do
- It does not fetch arbitrary certs — only Mozilla's curated root store.
- It does not verify the CCADB download signature.  The script URL is
  pinned; if Mozilla's domain is compromised, this script is not your
  trust anchor.  The generated bundle is reviewed in a PR before landing.
"""

import argparse
import base64
import hashlib
import re
import ssl
import sys
import textwrap
import urllib.request
from pathlib import Path

# -----------------------------------------------------------------------------
# Source configuration
# -----------------------------------------------------------------------------

CCADB_URL = (
    "https://ccadb-public.secure.force.com/mozilla/"
    "IncludedCACertificateReportPEMCSV"
)

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "src" / "stdlib" / "x509_roots.luna"
MAX_ROOTS   = 256                 # keep the array size bounded

# -----------------------------------------------------------------------------
# Fetch + parse CCADB
# -----------------------------------------------------------------------------

def fetch_ccadb() -> str:
    """Download the Mozilla root CA CSV (PEM-bundled)."""
    ctx = ssl.create_default_context()
    print(f"[regen_roots] GET {CCADB_URL}", file=sys.stderr)
    with urllib.request.urlopen(CCADB_URL, context=ctx, timeout=30) as r:
        return r.read().decode("utf-8", errors="replace")


def parse_roots(csv_text: str):
    """Extract (common_name, PEM-encoded DER) pairs from the CCADB CSV."""
    # The CSV is comma-separated but PEM blocks contain commas and newlines.
    # We search for the quoted PEM block directly.
    roots = []
    lines = csv_text.splitlines()
    header = lines[0].split(",")
    try:
        name_col = header.index("Common Name or Certificate Name")
        pem_col  = header.index('"PEM"'.strip('"'))
    except ValueError:
        # Some CCADB exports use slightly different column names — fall
        # back to heuristic "find a quoted field containing BEGIN CERT".
        name_col = 0
        pem_col  = -1

    for line in lines[1:]:
        # Find the quoted PEM block (contains "-----BEGIN CERTIFICATE-----")
        m = re.search(r'"(-----BEGIN CERTIFICATE-----[^"]+-----END CERTIFICATE-----)"', line)
        if not m:
            continue
        pem = m.group(1)
        # The CN is the first quoted field on the line
        cn_match = re.match(r'"([^"]+)"', line)
        cn = cn_match.group(1) if cn_match else "Unknown"
        roots.append((cn, pem))
    return roots


# -----------------------------------------------------------------------------
# SPKI hashing
# -----------------------------------------------------------------------------

def der_from_pem(pem: str) -> bytes:
    """Strip the PEM headers/footers and base64-decode to DER."""
    body = re.sub(r"-----BEGIN CERTIFICATE-----", "", pem)
    body = re.sub(r"-----END CERTIFICATE-----", "", body)
    body = re.sub(r"\s+", "", body)
    return base64.b64decode(body)


def extract_spki_sha256(der: bytes) -> bytes:
    """Parse a DER-encoded X.509 cert, find the SubjectPublicKeyInfo
    SEQUENCE, SHA-256 the full SPKI bytes (tag + length + content)."""
    try:
        from cryptography import x509
        from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat
    except ImportError:
        print("ERROR: install the 'cryptography' package (pip install cryptography)",
              file=sys.stderr)
        sys.exit(2)

    cert = x509.load_der_x509_certificate(der)
    spki_der = cert.public_key().public_bytes(
        Encoding.DER,
        PublicFormat.SubjectPublicKeyInfo,
    )
    return hashlib.sha256(spki_der).digest()


# -----------------------------------------------------------------------------
# Luna-source emitter
# -----------------------------------------------------------------------------

LUNA_HEADER = """\
# (c) 2026 Luna Ecosystem. Lead Architect: LMDtokyo. All rights reserved.
# Licensed under GPLv3. See LICENSE file.

# =============================================================================
# Luna X.509 Trust Store — Mozilla CA Bundle (v4.3)
# =============================================================================
# AUTO-GENERATED from Mozilla CCADB by bootstrap/regen_roots.py.
# Do NOT hand-edit — rerun the script and commit the result.
#
# Contains SubjectPublicKeyInfo SHA-256 fingerprints of every root CA in
# Mozilla's NSS trust store.  Consumed by veil.luna's x509_chain_verify.
# =============================================================================

import types
import crypto

"""

LUNA_FOOTER_TEMPLATE = """\
const TRUST_ROOT_COUNT: int = {count}

# Each root occupies 32 consecutive bytes; names are held in a separate
# offset+length table for human-readable diagnostics.

const TRUST_ROOT_SPKI: [int; {bytes}] = [
{bytes_block}
]

const TRUST_ROOT_NAME_OFFSETS: [int; {count}] = [
{offset_block}
]

const TRUST_ROOT_NAME_LENS: [int; {count}] = [
{length_block}
]

const TRUST_ROOT_NAMES: str = "{names_blob}"

# =============================================================================
# Trust-store API
# =============================================================================

fn trust_store_count() -> int
    return TRUST_ROOT_COUNT

fn trust_store_contains(@spki_hash_ptr: int) -> int
    orbit @i in 0..TRUST_ROOT_COUNT
        @match = 1
        orbit @j in 0..32
            @a = 0
            unsafe
                @a = volatile_read(@spki_hash_ptr + @j)
            if @a != TRUST_ROOT_SPKI[@i * 32 + @j]
                @match = 0
                break
        if @match == 1
            return 1
    return 0

fn trust_store_find(@spki_hash_ptr: int) -> int
    orbit @i in 0..TRUST_ROOT_COUNT
        @match = 1
        orbit @j in 0..32
            @a = 0
            unsafe
                @a = volatile_read(@spki_hash_ptr + @j)
            if @a != TRUST_ROOT_SPKI[@i * 32 + @j]
                @match = 0
                break
        if @match == 1
            return @i
    return -1

fn trust_store_name(@index: int, @out_ptr: int, @out_len: int) -> int
    if @index < 0 or @index >= TRUST_ROOT_COUNT
        return 0
    @off = TRUST_ROOT_NAME_OFFSETS[@index]
    @len = TRUST_ROOT_NAME_LENS[@index]
    @n = if @len < @out_len then @len else @out_len
    orbit @j in 0..@n
        @ch = 0
        unsafe
            @ch = volatile_read(TRUST_ROOT_NAMES + @off + @j)
            volatile_write(@out_ptr + @j, @ch)
    return @n

fn run_x509_roots_tests() -> int
    @pass = 0
    if TRUST_ROOT_COUNT > 0
        @pass = @pass + 1
    # First root's first byte non-zero (real hash, not placeholder)
    if TRUST_ROOT_SPKI[0] != 0 or TRUST_ROOT_SPKI[1] != 0
        @pass = @pass + 1
    meow @zero_probe: [int; 32] = [0; 32]
    if trust_store_contains(@zero_probe) == 0
        @pass = @pass + 1
    return @pass

export {
    TRUST_ROOT_COUNT, TRUST_ROOT_SPKI,
    TRUST_ROOT_NAME_OFFSETS, TRUST_ROOT_NAME_LENS, TRUST_ROOT_NAMES,
    trust_store_count, trust_store_contains, trust_store_find,
    trust_store_name, run_x509_roots_tests
}
"""


def format_bytes_block(roots) -> str:
    """Render the SPKI hashes as a grouped `[int; N]` initialiser."""
    lines = []
    for name, hash_bytes in roots:
        hex_row = ", ".join(f"0x{b:02x}" for b in hash_bytes)
        wrapped = textwrap.fill(hex_row, width=80, initial_indent="    ",
                                subsequent_indent="    ")
        lines.append(f"    # {name}")
        lines.append(wrapped + ",")
    return "\n".join(lines).rstrip(",")


def format_offsets(roots) -> str:
    offsets, pos = [], 0
    for name, _ in roots:
        offsets.append(pos)
        pos += len(name) + 1    # +1 for the NUL between names
    return "    " + ",\n    ".join(str(o) for o in offsets)


def format_lengths(roots) -> str:
    return "    " + ",\n    ".join(str(len(name)) for name, _ in roots)


def format_names_blob(roots) -> str:
    # Escape quotes, embed \0 between names for O(1) lookup by offset.
    parts = []
    for name, _ in roots:
        # Minimal escape: quotes and backslashes
        safe = name.replace("\\", "\\\\").replace('"', '\\"')
        parts.append(safe)
    return "\\0".join(parts)


# -----------------------------------------------------------------------------
# Driver
# -----------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--dry-run", action="store_true",
                    help="print hashes to stdout, do not rewrite the .luna file")
    ap.add_argument("--include-test", action="store_true",
                    help="include ISRG staging test CA (for dev only — not trusted in prod)")
    ap.add_argument("--output", default=str(OUTPUT_PATH),
                    help=f"output path (default: {OUTPUT_PATH})")
    args = ap.parse_args()

    try:
        csv_text = fetch_ccadb()
    except Exception as e:
        print(f"[regen_roots] ERROR fetching CCADB: {e}", file=sys.stderr)
        return 1

    roots_pem = parse_roots(csv_text)
    if not roots_pem:
        print("[regen_roots] ERROR: no roots parsed from CCADB", file=sys.stderr)
        return 1

    print(f"[regen_roots] parsed {len(roots_pem)} roots", file=sys.stderr)

    roots = []
    for name, pem in roots_pem:
        try:
            der = der_from_pem(pem)
            spki_hash = extract_spki_sha256(der)
            roots.append((name, spki_hash))
        except Exception as e:
            print(f"[regen_roots]   SKIP '{name}' — {e}", file=sys.stderr)

    if len(roots) > MAX_ROOTS:
        print(f"[regen_roots] WARNING: truncating from {len(roots)} to {MAX_ROOTS}",
              file=sys.stderr)
        roots = roots[:MAX_ROOTS]

    if args.dry_run:
        for name, h in roots:
            print(f"{h.hex()}  {name}")
        return 0

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    body = (
        LUNA_HEADER +
        LUNA_FOOTER_TEMPLATE.format(
            count=len(roots),
            bytes=len(roots) * 32,
            bytes_block=format_bytes_block(roots),
            offset_block=format_offsets(roots),
            length_block=format_lengths(roots),
            names_blob=format_names_blob(roots),
        )
    )
    out_path.write_text(body, encoding="utf-8")
    print(f"[regen_roots] wrote {len(roots)} roots to {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
